version: '3.8'

services:
  # SSE MCP Server
  mcp-sse-server:
    build:
      context: .
      dockerfile: Dockerfile.sse
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WebSocket MCP Server
  mcp-websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8002:8002"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HTTP MCP Server
  mcp-http-server:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8003:8003"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test Client (optional)
  mcp-test-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - mcp-sse-server
      - mcp-websocket-server
      - mcp-http-server
    networks:
      - mcp-network
    environment:
      - SSE_URL=http://mcp-sse-server:8001/mcp/sse
      - WS_URL=ws://mcp-websocket-server:8002/mcp/ws
      - HTTP_URL=http://mcp-http-server:8003/mcp
    command: ["python", "client_examples/test_all_transports.py"]

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data: